### ISSUE TITLE
ModuleNotFoundError: No module named 'dbus'

### ISSUE THREAD

**Issue by kiven7299** [marcnewlin/hi_my_name_is_keyboard#11]
Hi there,

I have installed all the required dependencies as mentioned [here](https://github.com/marcnewlin/hi_my_name_is_keyboard?tab=readme-ov-file#dependencies). However, when I executed the python script "keystroke-injection-android-linux.py", it raised error:
```
Traceback (most recent call last):
  File "/mnt/d/Tools/hi_my_name_is_keyboard/./keystroke-injection-android-linux.py", line 11, in <module>
    from injector.agent import PairingAgent
  File "/mnt/d/Tools/hi_my_name_is_keyboard/injector/agent.py", line 1, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

I'm using kali wsl. It does have `pydbus` python package but not `dbus`. I have tried to install legacy `dbus-python` package but it failed to install. How to fix this problem?
![image](https://github.com/marcnewlin/hi_my_name_is_keyboard/assets/60765640/5c265f9b-d328-4236-835e-81273e10e326)

Thank you and have a great day!

**Comment by cobra-c313** [comment]
Yeah, im having the same issue. After much digging, I have concluded that dbus-python is not working well with python3.10, we have to use a previous version to make it install successfully

**Comment by kiven7299** [comment]
Thank you @cobra-c313, which version that you use?

**Comment by Neowizard** [comment]
You can install `python3-dbus` using `apt`. It should resolve your missing dependency issue
