### ISSUE TITLE
Can we scan the all of the Bluetooth devices near us with this tool ?

### ISSUE THREAD

**Issue by Ali-Hastam** [marcnewlin/hi_my_name_is_keyboard#3]
can we ?

**Comment by pentestfunctions** [comment]
This doesn't scan, but my script has a scanner in it. 
You could also try manually scan using
```bash
bluetoothctl
power on
discoverable on
pairable on
agent NoInputNoOutput
default-agent
scan on
```

**Comment by Ali-Hastam** [comment]
> This doesn't scan, but my script has a scanner in it. You could also try manually scan using
> 
> ```shell
> bluetoothctl
> power on
> discoverable on
> pairable on
> agent NoInputNoOutput
> default-agent
> scan on
> ```

Thanks 🖐️

**Comment by Waellovee** [comment]
How i fix this in nethunter 
Traceback (most recent call last): File "/root/hi_my_name_is_keyboard/./keystroke-injection-android-linux.py", line 9, in <module> from injector.client import KeyboardClient File "/root/hi_my_name_is_keyboard/injector/client.py", line 2, in <module> import bluetooth ModuleNotFoundError: No module named 'bluetooth'
![Screenshot_20240124-102615](https://github.com/marcnewlin/hi_my_name_is_keyboard/assets/104840332/954ea716-d124-441e-a5a1-eb62df83b63e)

**Comment by Ali-Hastam** [comment]
> This doesn't scan, but my script has a scanner in it. You could also try manually scan using
> 
> ```shell
> bluetoothctl
> power on
> discoverable on
> pairable on
> agent NoInputNoOutput
> default-agent
> scan on
> ```

And I have another question ....
Do u know how i can use my own payload with this tool (Payload for android)?

**Comment by cobra-c313** [comment]
> > This doesn't scan, but my script has a scanner in it. You could also try manually scan using
> > ```shell
> > bluetoothctl
> > power on
> > discoverable on
> > pairable on
> > agent NoInputNoOutput
> > default-agent
> > scan on
> > ```
> 
> And I have another question .... Do u know how i can use my own payload with this tool (Payload for android)?

Im not yet sure about that, in theory, we have to edit hid.py module in injector dir
