### ISSUE TITLE
How i fix this (Nethunter)

### ISSUE THREAD

**Issue by Waellovee** [marcnewlin/hi_my_name_is_keyboard#4]
How i fix this in nethunter
Traceback (most recent call last): File "/root/hi_my_name_is_keyboard/./keystroke-injection-android-linux.py", line 9, in from injector.client import KeyboardClient File "/root/hi_my_name_is_keyboard/injector/client.py", line 2, in import bluetooth ModuleNotFoundError: No module named 'bluetooth'
![Screenshot_20240124-102615](https://github.com/marcnewlin/hi_my_name_is_keyboard/assets/104840332/951cb731-cd13-4db9-bebf-f8602a527d8d)

**Comment by Ali-Hastam** [comment]
> How i fix this in nethunter Traceback (most recent call last): File "/root/hi_my_name_is_keyboard/./keystroke-injection-android-linux.py", line 9, in from injector.client import KeyboardClient File "/root/hi_my_name_is_keyboard/injector/client.py", line 2, in import bluetooth ModuleNotFoundError: No module named 'bluetooth' ![Screenshot_20240124-102615](https://private-user-images.githubusercontent.com/104840332/299228656-951cb731-cd13-4db9-bebf-f8602a527d8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTE2MDUsIm5iZiI6MTcwNjExMTMwNSwicGF0aCI6Ii8xMDQ4NDAzMzIvMjk5MjI4NjU2LTk1MWNiNzMxLWNkMTMtNGRiOS1iZWJmLWY4NjAyYTUyN2Q4ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxNTQ4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZmNjYwMThhNGRiZDM5N2ZiYWYwYTVlZDg3MDAwMWNkOThjMmRlZjU0ZDQwZWI4NjAyNjk0MDM0YTc5Zjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A0xLVaW1eCYiRGSN2UYIUQp01VY8DGiYpBiLyhbCX9E)

Hey 
You can do this :
sudo aptitude install python-bluez
sudo apt-get update
sudo apt-get upgrade

Done :)

**Comment by Waellovee** [comment]
Thank you Ali very much

**Comment by dr1408** [comment]
Did it work on nethunter I got some errors
